### ISSUE TITLE
Verfügbarkeit

### ISSUE THREAD

**Issue by JohnnyTheTank** [sp3rk/coachingWebApp#36]
Hallo,

ist die App in einem Appstore verfügbar?

Grüße

**Comment by sp3rk** [comment]
Servus.
Nein, aktuell noch nicht da momentan nur die Verwaltung eines Vereins (vordefiniert) funktioniert.

Da ich leider nicht sehr viel Zeit habe um an der "app" zu arbeiten, wird's wohl auch noch ne Weile dauern, bis ich dir da was anbieten kann.

**Comment by JohnnyTheTank** [comment]
ich bin zufällig drauf gestoßen, da ich gesehen habe, dass du [angular-youtube-api-factory](https://github.com/JohnnyTheTank/angular-youtube-api-factory) nutzt, welches ich entwickelt habe.

nutzt du ionic 1 oder 2?

**Comment by sp3rk** [comment]
In der alten bzw. aktuellen Version ionic 1. (deine API funktioniert ;-) )
Ich werd' was ähnliches auch für ionic2/angular2 brauchen...aber wie gesagt...ich arbeite mich gerade erst in die 2er Versionen ein.
